// ********RoostGPT********
/*
Test generated by RoostGPT for test go-test-examples using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=Sum_12da9b9283
ROOST_METHOD_SIG_HASH=Sum_dfd8630463

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-test-examples/01-normal/normal_test.go
Test Cases:
    [TestSum]

Note: Only generate test cases based on the given scenarios,do not generate test cases other than these scenarios
Scenario 1: {Description:Test scenario where both input numbers are negative integers
Scenario 2: selected:true}
Scenario 3: {Description:Test scenario where one input number is positive and the other is negative
Scenario 4: {Description:Test scenario where both input numbers are zero
*/

// ********RoostGPT********
package main

import (
	"fmt"
)

// Sum function adds two integers and returns the result
func Sum(x, y int) int {
	z := x + y
	return z
}

func main() {
	fmt.Println(Sum(5, 7)) // expects 12
}
